name: Import open source standard labels

on:
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: EddieHubCommunity/gh-action-open-source-labels@v0.2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner-name: ${{ github.repository_owner }}
          repository-name: ${{ github.event.repository.name }}
